<?php

namespace FluxEco\Projection\Adapters\Configs;

class ProjectionEnv
{
    public const PARAM_DATABASE = 'PROJECTION_MYSQL_DATABASE';
    public const PARAM_APP_PROJECTION_SCHEMA_DIRECTORY = 'APP_PROJECTION_SCHEMA_DIRECTORY';
    public const PARAM_ECO_PROJECTION_SCHEMA_DIRECTORY = 'ECO_PROJECTION_SCHEMA_DIRECTORY';
}